package internal

var FileIcons = map[string]string{
	"go":         "\ue627",
	"sum":        "\ue627",
	"mod":        "\ue627",
	"log":        "\ued81",
	"md":         "\ue73b",
	"js":         "\uf2ef",
	"jsx":        "\uf2ef",
	"ts":         "\ue8ca",
	"tsx":        "\ue8ca",
	"json":       "\ueb0f",
	"yaml":       "\ue6a8",
	"yml":        "\ue6a8",
	"toml":       "\ue6b2",
	"html":       "\ue736",
	"css":        "\ue749",
	"php":        "\ue608",
	"rs":         "\ue68b",
	"wav":        "\uf001",
	"zip":        "\ue6aa",
	"py":         "\ued1b",
	"txt":        "\uf15c",
	"pdf":        "\uf1c1",
	"png":        "\uf03e",
	"jpg":        "\uf03e",
	"webp":       "\uf03e",
	"jpeg":       "\uf03e",
	"tif":        "\uf03e",
	"sh":         "\uf489",
	"license":    "\ue60a",
	"gitignore":  "\ue702",
	"dockerfile": "\uf21f",
}
